import{CONFIG,addAppointment,addBlock,availableSlots,cancelAppointment,createInitialState,createSlots,loadState,removeBlock,saveState,updateAppointment,upsertService,whatsappUrl}from'./store.js';
let state=loadState();
const $=id=>document.getElementById(id);const today=new Date().toISOString().slice(0,10);
function persist(){saveState(state);render();}
function money(v){return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}function service(id){return state.services.find(s=>s.id===id);}
function fillSlots(select,date,ignoreId){select.innerHTML='';const slots=availableSlots(state,date,ignoreId);if(!date){select.add(new Option('Escolha um dia primeiro',''));return}if(!slots.length){select.add(new Option('Sem horários disponíveis',''));return}slots.forEach(t=>select.add(new Option(t,t)));}
function renderServices(){const sel=$('serviceSelect');sel.innerHTML='';state.services.forEach(s=>sel.add(new Option(`${s.name} — ${money(s.price)}`,s.id)));$('servicesList').innerHTML=state.services.map(s=>`<div class="row"><strong>${s.name}</strong><span>${money(s.price)}</span><button data-edit-service="${s.id}">Editar</button></div>`).join('');}
function renderBlocks(){const select=$('blockTime');select.innerHTML='<option value="">Dia inteiro</option>';createSlots().forEach(t=>select.add(new Option(t,t)));$('blocksList').innerHTML=state.blocks.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(b=>`<div class="row"><span><strong>${b.date}</strong> ${b.time||'dia inteiro'}<small>${b.reason||''}</small></span><button data-remove-block="${b.id}">Remover</button></div>`).join('')||'<p class="muted">Nenhum bloqueio cadastrado.</p>';}
function renderAppointments(){const day=$('adminDate').value;let items=state.appointments.filter(a=>!day||a.date===day).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('appointmentsList').innerHTML=items.map(a=>`<article class="appointment ${a.status}"><div><strong>${a.time} — ${a.name}</strong><p>${a.serviceName} · ${money(a.price)} · ${a.phone}</p><small>${a.date} · ${a.status}</small></div><div class="actions"><button data-edit-appt="${a.id}" ${a.status==='cancelado'?'disabled':''}>Alterar</button><button data-cancel="${a.id}" ${a.status==='cancelado'?'disabled':''}>Cancelar</button></div><div id="edit-${a.id}"></div></article>`).join('')||'<p class="muted">Nenhum agendamento para este filtro.</p>';}
function render(){renderServices();fillSlots($('timeSelect'),$('dateInput').value);renderBlocks();renderAppointments();}
['dateInput','adminDate'].forEach(id=>$(id).min=today);$('dateInput').value=today;$('adminDate').value=today;$('blockDate').min=today;
$('dateInput').addEventListener('change',()=>fillSlots($('timeSelect'),$('dateInput').value));
$('bookingForm').addEventListener('submit',e=>{e.preventDefault();try{const appt=addAppointment(state,{serviceId:$('serviceSelect').value,date:$('dateInput').value,time:$('timeSelect').value,name:$('nameInput').value,phone:$('phoneInput').value});saveState(state);$('confirmation').classList.remove('hidden');$('confirmation').innerHTML=`<strong>Agendamento confirmado!</strong><p>${appt.name}, ${appt.serviceName} em ${appt.date} às ${appt.time}.</p><a class="whatsapp" target="_blank" rel="noopener" href="${whatsappUrl(appt)}">Abrir WhatsApp</a>`;$('bookingForm').reset();$('dateInput').value=today;render();}catch(err){alert(err.message);}});
$('serviceForm').addEventListener('submit',e=>{e.preventDefault();try{upsertService(state,{id:$('serviceId').value,name:$('serviceName').value,price:$('servicePrice').value});e.target.reset();persist();}catch(err){alert(err.message);}});
$('blockForm').addEventListener('submit',e=>{e.preventDefault();try{addBlock(state,{date:$('blockDate').value,time:$('blockTime').value,reason:$('blockReason').value});e.target.reset();persist();}catch(err){alert(err.message);}});
$('adminDate').addEventListener('change',renderAppointments);$('seedButton').addEventListener('click',()=>{if(confirm('Restaurar serviços iniciais e apagar agendamentos/bloqueios?')){state=createInitialState();persist();}});
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.editService){const s=service(t.dataset.editService);$('serviceId').value=s.id;$('serviceName').value=s.name;$('servicePrice').value=s.price;scrollTo({top:$('serviceForm').offsetTop-20,behavior:'smooth'});}if(t.dataset.removeBlock){removeBlock(state,t.dataset.removeBlock);persist();}if(t.dataset.cancel){if(confirm('Cancelar agendamento?')){cancelAppointment(state,t.dataset.cancel);persist();}}if(t.dataset.editAppt){const a=state.appointments.find(x=>x.id===t.dataset.editAppt);const host=$(`edit-${a.id}`);host.innerHTML=$('editTemplate').innerHTML;const form=host.querySelector('form');form.date.value=a.date;fillSlots(form.time,a.date,a.id);form.time.value=a.time;form.date.addEventListener('change',()=>fillSlots(form.time,form.date.value,a.id));form.addEventListener('submit',ev=>{ev.preventDefault();try{updateAppointment(state,a.id,{date:form.date.value,time:form.time.value});persist();}catch(err){alert(err.message);}});}});
render();
