export const CONFIG={businessPhone:"5511999999999",slotStart:"09:00",slotEnd:"18:00",slotMinutes:30,storageKey:"barbearia.v1"};
export const defaultServices=[{id:"corte",name:"Corte",price:40},{id:"barba",name:"Barba",price:40},{id:"corte-barba",name:"Corte + Barba",price:80}];
export function createInitialState(){return{services:[...defaultServices],appointments:[],blocks:[]};}
export function createSlots(cfg=CONFIG){const slots=[];let [h,m]=cfg.slotStart.split(':').map(Number);const [eh,em]=cfg.slotEnd.split(':').map(Number);while(h*60+m<eh*60+em){slots.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);m+=cfg.slotMinutes;h+=Math.floor(m/60);m%=60;}return slots;}
export function loadState(storage=localStorage){try{return JSON.parse(storage.getItem(CONFIG.storageKey))||createInitialState();}catch{return createInitialState();}}
export function saveState(state,storage=localStorage){storage.setItem(CONFIG.storageKey,JSON.stringify(state));}
export function isBlocked(state,date,time){return state.blocks.some(b=>b.date===date&&(b.time===""||b.time===time));}
export function isOccupied(state,date,time,ignoreId=null){return state.appointments.some(a=>a.date===date&&a.time===time&&a.status!=="cancelado"&&a.id!==ignoreId);}
export function availableSlots(state,date,ignoreId=null){return createSlots().filter(t=>!isBlocked(state,date,t)&&!isOccupied(state,date,t,ignoreId));}
export function addAppointment(state,input){if(!input.serviceId||!input.date||!input.time||!input.name||!input.phone)throw new Error('Preencha todos os dados.');if(isBlocked(state,input.date,input.time))throw new Error('Horário bloqueado.');if(isOccupied(state,input.date,input.time))throw new Error('Horário já ocupado.');const service=state.services.find(s=>s.id===input.serviceId);if(!service)throw new Error('Serviço inválido.');const appt={id:crypto.randomUUID?.()||String(Date.now()),serviceId:service.id,serviceName:service.name,price:service.price,date:input.date,time:input.time,name:input.name.trim(),phone:input.phone.trim(),status:'confirmado',createdAt:new Date().toISOString()};state.appointments.push(appt);return appt;}
export function cancelAppointment(state,id){const a=state.appointments.find(x=>x.id===id);if(!a)throw new Error('Agendamento não encontrado.');a.status='cancelado';return a;}
export function updateAppointment(state,id,changes){const a=state.appointments.find(x=>x.id===id);if(!a)throw new Error('Agendamento não encontrado.');const date=changes.date??a.date,time=changes.time??a.time;if(isBlocked(state,date,time))throw new Error('Horário bloqueado.');if(isOccupied(state,date,time,id))throw new Error('Horário já ocupado.');Object.assign(a,changes,{date,time});return a;}
export function upsertService(state,{id,name,price}){if(!name||price===''||Number(price)<0)throw new Error('Informe serviço e preço.');const data={id:id||name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:name.trim(),price:Number(price)};const i=state.services.findIndex(s=>s.id===data.id);i>=0?state.services.splice(i,1,data):state.services.push(data);return data;}
export function addBlock(state,{date,time='',reason=''}){if(!date)throw new Error('Informe o dia.');const b={id:crypto.randomUUID?.()||String(Date.now()),date,time,reason:reason.trim()};state.blocks.push(b);return b;}
export function removeBlock(state,id){state.blocks=state.blocks.filter(b=>b.id!==id);}
export function whatsappUrl(appt,phone=CONFIG.businessPhone){const msg=`Olá! Confirmo meu agendamento: Nome: ${appt.name}, Serviço: ${appt.serviceName}, Data: ${appt.date}, Horário: ${appt.time}.`;return `https://wa.me/${phone}?text=${encodeURIComponent(msg)}`;}
